# Generated by Django 4.2.6 on 2023-10-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0003_residential_villa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Commer/')),
            ],
        ),
        migrations.AlterField(
            model_name='plot_dev',
            name='image',
            field=models.ImageField(upload_to='Plot/'),
        ),
        migrations.AlterField(
            model_name='residential_villa',
            name='image',
            field=models.ImageField(upload_to='Reside/'),
        ),
    ]
