# Generated by Django 4.2.6 on 2023-10-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0007_cosmetics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Bg_export/')),
            ],
        ),
    ]
