# Generated by Django 4.2.6 on 2023-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0008_bg_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_export',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Bg_export/'),
        ),
    ]
