# Generated by Django 4.2.6 on 2023-10-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0009_alter_bg_export_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Health/')),
            ],
        ),
    ]
