# Generated by Django 4.2.6 on 2023-10-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0010_health_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_care',
            name='title',
        ),
    ]
