# Generated by Django 4.2.6 on 2023-10-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0011_remove_health_care_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Bg_Health/')),
            ],
        ),
    ]
