# Generated by Django 4.2.6 on 2023-10-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0012_bg_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_constr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
