# Generated by Django 4.2.6 on 2023-10-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0013_start_constr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
