# Generated by Django 4.2.6 on 2023-10-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0014_start_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='side_img_consulting/')),
            ],
        ),
    ]
