# Generated by Django 4.2.6 on 2023-10-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0015_img_consulting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StratUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Startup/')),
            ],
        ),
    ]
