# Generated by Django 4.2.6 on 2023-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0016_stratup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Construction/')),
            ],
        ),
    ]
