# Generated by Django 4.2.6 on 2023-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0019_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_1', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Client/')),
            ],
        ),
    ]
