# Generated by Django 4.2.6 on 2023-10-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0020_home_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_heading',
            name='description',
        ),
        migrations.RemoveField(
            model_name='home_heading',
            name='image',
        ),
    ]
