# Generated by Django 4.2.6 on 2023-11-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0022_stratup_image_1_stratup_image_2_alter_stratup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Construction/'),
        ),
        migrations.AddField(
            model_name='construction',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Construction/'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Construction/'),
        ),
    ]
