# Generated by Django 4.2.6 on 2023-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0023_construction_image_1_construction_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Infrastructure/'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Infrastructure/'),
        ),
    ]
