# Generated by Django 4.2.6 on 2023-11-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0024_infrastructure_image_1_infrastructure_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Commer/'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Commer/'),
        ),
        migrations.AddField(
            model_name='land_acq',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='land/'),
        ),
        migrations.AddField(
            model_name='land_acq',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='land/'),
        ),
        migrations.AddField(
            model_name='plot_dev',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Plot/'),
        ),
        migrations.AddField(
            model_name='plot_dev',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Plot/'),
        ),
        migrations.AddField(
            model_name='residential_villa',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Reside/'),
        ),
        migrations.AddField(
            model_name='residential_villa',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Reside/'),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Commer/'),
        ),
        migrations.AlterField(
            model_name='land_acq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='land/'),
        ),
        migrations.AlterField(
            model_name='plot_dev',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Plot/'),
        ),
        migrations.AlterField(
            model_name='residential_villa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Reside/'),
        ),
    ]
