# Generated by Django 4.2.6 on 2023-11-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0025_commercial_image_1_commercial_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cosmetics/'),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
        migrations.AddField(
            model_name='spices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spices/'),
        ),
    ]
