# Generated by Django 4.2.6 on 2023-11-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0026_cosmetics_image_food_image_spices_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_care',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Health/'),
        ),
        migrations.AddField(
            model_name='health_care',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Health/'),
        ),
        migrations.AlterField(
            model_name='health_care',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Health/'),
        ),
    ]
