# Generated by Django 4.2.6 on 2023-11-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbainc', '0027_health_care_image_1_health_care_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Mining/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='Mining/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='Mining/')),
            ],
        ),
    ]
